# Generated by Django 4.2.2 on 2023-06-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_image_in_image_out_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="sat",
            field=models.IntegerField(default=1.3),
            preserve_default=False,
        ),
    ]
